- backports=1.0=py27_0
- decorator=4.0.10=py27_0
- docopt=0.6.2=py27_0
- get_terminal_size=1.0.0=py27_0
- ipython=5.1.0=py27_0
- ipython_genutils=0.1.0=py27_0
- mkl=11.3.3=0
- numexpr=2.6.1=np111py27_0
- numpy=1.11.1=py27_0
- openssl=1.0.2h=1
- pandas=0.18.1=np111py27_0
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- pexpect=4.0.1=py27_0
- pickleshare=0.7.3=py27_0
- pip=8.1.2=py27_0
- prompt_toolkit=1.0.3=py27_0
- ptyprocess=0.5.1=py27_0
- pygments=2.1.3=py27_0
- python=2.7.12=1
- python-dateutil=2.5.3=py27_0
- pytz=2016.6.1=py27_0
- readline=6.2=2
- setuptools=26.1.1=py27_0
- simplegeneric=0.8.1=py27_1
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- traitlets=4.2.2=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
  - backports.shutil-get-terminal-size==1.0.0
  - bottleneck==1.1.0
  - colorlover==0.2.1
  - cufflinks==0.8.2
  - google-api-python-client==1.5.3
  - gspread==0.4.1
  - httplib2==0.9.2
  - ipython-genutils==0.1.0
  - oauth2client==3.0.0
  - plotly==1.12.9
  - prompt-toolkit==1.0.3
  - pyasn1==0.1.9
  - pyasn1-modules==0.0.8
  - requests==2.11.1
  - rsa==3.4.2
  - simplejson==3.8.2
  - termcolor==1.1.0
  - uritemplate==0.6
  - urllib3==1.16
  - xlsxwriter==0.9.3

